---
title: "(SCRIPT) COVID-19: Gross Domestic Product and vaccination rate analysis."
author: "Paulo Rocha 919098831"
date: "03/04/2022"
output:
  html_document:
    df_print: paged
    number_sections: yes
    toc: true
    toc_depth: 2
    toc_float: true
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```

***

# Descriptive analysis

```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
library(tidyverse)
library(patchwork)
library(gplots)
library(kableExtra)
library(qwraps2)
options(qwraps2_markup = "latex")

who_cases <- read_csv("https://covid19.who.int/WHO-COVID-19-global-data.csv")
who_vaccine <- read_csv("https://covid19.who.int/who-data/vaccination-data.csv")
pop = read_csv("datasets/WPP2019_TotalPopulationBySex.csv")

dim(pop)
dim(who_cases)
dim(who_vaccine)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
who_cases <- who_cases %>% 
  filter(WHO_region != "Other") %>% 
  mutate(WHO_region = fct_recode(WHO_region,"Eastern Mediterranean"="EMRO","Europe" = "EURO","Africa" = "AFRO",
                                 "Western Pacific" = "WPRO","Americas"="AMRO","South-East Asia" = "SEARO"))

range(who_cases$Date_reported)
length(unique(who_cases$Country))

who_cases_region <- who_cases %>%
  select(!c(2,3)) %>%
  group_by(Date_reported, WHO_region) %>%
  summarise_each(funs(sum))

who_cases_region$Case_mortality_rate <- who_cases_region$Cumulative_deaths/who_cases_region$Cumulative_cases
who_cases_region$Case_mortality_rate[is.nan(who_cases_region$Case_mortality_rate)] <- 0

length(unique(who_cases$WHO_region))
```


```{r, echo=FALSE, fig.height=8, fig.width=12}

f1 <- ggplot(who_cases_region, aes(x = Date_reported, y = New_cases)) +
  geom_line(aes(color = WHO_region))+
  scale_x_continuous(breaks = pretty(who_cases_region$Date_reported, n = 12)) +
  labs(x = "Date reported", y = "New cases",color='WHO region')

f2 <- ggplot(who_cases_region, aes(x = Date_reported, y = New_deaths)) +
  geom_line(aes(color = WHO_region)) +
  scale_x_continuous(breaks = pretty(who_cases_region$Date_reported, n = 12)) +
  guides(color="none") +
  labs(x = "Date reported", y = "New deaths",color='WHO region')


(f1 / f2) + plot_annotation(
  title = 'Figure 1. New cases and new deaths overtime.',
  theme = theme(plot.title = element_text(hjust = 0.5))
)
```


```{r, echo=FALSE, fig.height=8, fig.width=12}
f1 <- ggplot(who_cases_region, aes(x = Date_reported, y = Cumulative_cases)) +
  geom_line(aes(color = WHO_region))+
  scale_x_continuous(breaks = pretty(who_cases_region$Date_reported, n = 12)) +
  labs(x = "Date reported", y = "Cumulative cases",color='WHO region')

f2 <- ggplot(who_cases_region, aes(x = Date_reported, y = Cumulative_deaths)) +
  geom_line(aes(color = WHO_region)) +
  scale_x_continuous(breaks = pretty(who_cases_region$Date_reported, n = 12)) +
  guides(color="none")+
  labs(x = "Date reported", y = "Cumulative deaths")


(f1 / f2) + plot_annotation(
  title = 'Figure 2. Cumulative cases and deaths overtime.',
  theme = theme(plot.title = element_text(hjust = 0.5))
)
```


```{r, echo=FALSE, fig.height=4, fig.width=12}

f1 <- ggplot(who_cases_region, aes(x = Date_reported, y = Case_mortality_rate)) +
  geom_line(aes(color = WHO_region)) +
  scale_x_continuous(breaks = pretty(who_cases_region$Date_reported, n = 12)) +
  labs(x = "Date reported", y = "Case-mortality rate",color='WHO region')


f1 + plot_annotation(
  title = 'Figure 3. Case-mortality rate overtime.',
  theme = theme(plot.title = element_text(hjust = 0.5))
)
```


```{r, echo=FALSE, fig.height=4, fig.width=14}
our_summary1 <-
  list("New_cases" =
       list("median"    = ~ median(New_cases),
            "max"       = ~ max(New_cases)),
       "Cumulative_cases" =
       list("median"    = ~ median(Cumulative_cases),
            "max"       = ~ max(Cumulative_cases)),
       "New_deaths" =
       list("median"    = ~ median(New_deaths),
            "max"       = ~ max(New_deaths)),
       "Cumulative_deaths" =
       list("median"    = ~ median(Cumulative_deaths),
            "max"       = ~ max(Cumulative_deaths)),
       "Case_mortality_rate" =
       list("median"    = ~ median(Case_mortality_rate),
            "max"       = ~ max(Case_mortality_rate))
       )

summary_table(dplyr::group_by(who_cases_region, WHO_region), our_summary1) %>%
  kbl(caption = "Table 1. Summary statistics, median and max values.") %>%
  pack_rows("New cases", 1, 2) %>%
  pack_rows("Cumulative cases", 3, 4) %>%
  pack_rows("New deaths", 5, 6) %>%
  pack_rows("Cumulative deaths", 7, 8) %>%
  pack_rows("Case-mortality rate", 9, 10) %>%
  kable_classic(full_width = F, html_font = "Cambria")
  
```


```{r, echo=FALSE, fig.height=6, fig.width=12}
pop.2022 <- pop %>% 
  filter(Time == 2020, Variant == "Medium") %>% 
  mutate(Country=Location)

pop.2022$PopTotal <- pop.2022$PopTotal*1000 
who_cases.today <- who_cases %>% 
  filter(Date_reported == "2022-02-17")

who_cases.today.pop <- left_join(who_cases.today, pop.2022, by="Country")

who_cases.today.pop$Cases_per_pop <- who_cases.today.pop$Cumulative_cases/who_cases.today.pop$PopTotal
who_cases.today.pop$Deaths_per_pop <- who_cases.today.pop$Cumulative_deaths/who_cases.today.pop$PopTotal

who_cases.top.cases <- who_cases.today[order(-who_cases.today$Cumulative_cases),][1:5,] %>%                              
  mutate(Country = factor(Country, Country))

who_cases.top.deaths <- who_cases.today[order(-who_cases.today$Cumulative_deaths),][1:5,] %>%                              
  mutate(Country = factor(Country, Country))

who_cases.top.cases.pop <- who_cases.today.pop[order(-who_cases.today.pop$Cases_per_pop),][1:5,] %>%                              
  mutate(Country = factor(Country, Country))

who_cases.top.deaths.pop <- who_cases.today.pop[order(-who_cases.today.pop$Deaths_per_pop),][1:5,] %>%                              
  mutate(Country = factor(Country, Country))



f1 <- ggplot(data=who_cases.top.cases, aes(x=Cumulative_cases, y=Country)) +
  geom_bar(stat="identity", width = 0.5) +
  labs(x = "Cumulative cases", y = "Country")


f2 <- ggplot(data=who_cases.top.deaths, aes(x=Cumulative_deaths, y=Country)) +
  geom_bar(stat="identity", width = 0.5) +
  theme(axis.title.y=element_blank())+
  labs(x = "Cumulative deaths")

f3 <- ggplot(data=who_cases.top.cases.pop, aes(x=Cases_per_pop, y=Country)) + 
  geom_bar(stat="identity", width = 0.5) +
  labs(x = "Cases rate (cases/pop)", y = "Country")

f4 <- ggplot(data=who_cases.top.deaths.pop, aes(x=Deaths_per_pop, y=Country)) + 
  geom_bar(stat="identity", width = 0.5) +
  theme(axis.title.y=element_blank())+
  labs(x = "Deaths rate (deaths/pop)")


((f1 + f2) / (f3 + f4)) + plot_annotation(
  title = 'Figure 4. Countries with highest cumulative cases and deaths.',
  theme = theme(plot.title = element_text(hjust = 0.5))
)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
who_vaccine <- who_vaccine %>% 
  mutate(Country=COUNTRY)

who_cases.today.pop.vaccine <- inner_join(who_cases.today.pop, who_vaccine, by="Country")

who_cases.today.pop.vaccine$Cases_per_pop100 <- who_cases.today.pop.vaccine$Cases_per_pop*100
who_cases.today.pop.vaccine$Deaths_per_pop100 <- who_cases.today.pop.vaccine$Deaths_per_pop*100


length(unique(who_vaccine$Country))
length(unique(who_cases.today.pop.vaccine$Country))

```

```{r,echo=FALSE, fig.height=6, fig.width=12}
plotmeans(PERSONS_FULLY_VACCINATED_PER100 ~ WHO_region,data=who_cases.today.pop.vaccine,cex.lab=1.5,
          main="Figure 5. Pop fully vaccinated % means",xlab="WHO regions",  ylab="Pop fully vaccinated %") 
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
gdp <- read.csv("datasets/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_3632113.csv")
country.code <- read.csv("datasets/country_code.csv")
country.code <- country.code %>% 
  mutate(Country.Code=Alpha.3.code)

gdp <- inner_join(country.code, gdp, by="Country.Code")

who_cases.today.pop.vaccine <- who_cases.today.pop.vaccine %>% 
  mutate(Alpha.2.code=Country_code)

who_cases.today.pop.vaccine.gdp <- inner_join(who_cases.today.pop.vaccine, gdp, by="Alpha.2.code")

df.fit <- drop_na(who_cases.today.pop.vaccine.gdp[,c("COUNTRY", "WHO_region", "PERSONS_FULLY_VACCINATED_PER100", "Cases_per_pop100", "Deaths_per_pop100", "X2020")])
df.fit <- df.fit %>% 
  mutate(GDP_2020=X2020) %>% 
  mutate(Pop_fully_vaccinated=PERSONS_FULLY_VACCINATED_PER100)

```


```{r,fig.height=6, fig.width=12,echo=FALSE, warning=FALSE, message=FALSE }
plotmeans(GDP_2020 ~ WHO_region,df.fit,cex.lab=1.5,
          main="Figure 6. Gross Domestic Product (GDP)",xlab="WHO regions",  ylab="GDP $") 
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
df.cor <- df.fit[,c(4,5,7,8)]

colnames(df.cor) <- c("Cases per pop %",	"Deaths per pop %",	"GDP", "Pop fully vaccinated %")

cor(df.cor) %>%
  kbl(caption = "Table 3. Correlation matrix.") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

fit <- lm(Pop_fully_vaccinated ~ Cases_per_pop100 + Deaths_per_pop100 + GDP_2020, data=df.fit)

#define weights to use
wt <- 1 / lm(abs(fit$residuals) ~ fit$fitted.values)$fitted.values^2

#perform weighted least squares regression
fit.wls <- lm(Pop_fully_vaccinated ~ Cases_per_pop100 + Deaths_per_pop100 + GDP_2020, data = df.fit, weights=wt)

fit.wls.coefficients <- summary(fit.wls)$coefficients

rownames(fit.wls.coefficients) <- c("(Intercept)", "Cases per pop %",	"Deaths per pop %", "GDP")

fit.wls.coefficients %>%
  kbl(caption = "Table 4. WLS model coefficients for Pop fully vaccinated %.") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```


```{r,fig.height=6, fig.width=12,echo=FALSE, warning=FALSE, message=FALSE }


p1 <- ggplot(df.fit, aes(x=PERSONS_FULLY_VACCINATED_PER100)) + 
    geom_histogram(alpha=0.5, position="identity", bins = 15) +
  labs(x = "Pop fully vaccinated %", y = "Count")

p2 <- ggplot(df.fit, aes(x=Cases_per_pop100)) + 
    geom_histogram(alpha=0.5, position="identity", bins = 15) +
  labs(x = "Cases per pop %", y = "Count")
    
p3 <- ggplot(df.fit, aes(x=Deaths_per_pop100)) + 
    geom_histogram(alpha=0.5, position="identity", bins = 15) +
  labs(x = "Deaths per pop %", y = "Count")

p4 <- ggplot(df.fit, aes(x=GDP_2020)) + 
    geom_histogram(alpha=0.5, position="identity", bins = 15) +
  labs(x = "GDP", y = "Count")

((p1 | p2) / (p3 | p4)) + plot_annotation(
  title = 'Figure 7. Variables histogram',
  theme = theme(plot.title = element_text(hjust = 0.5))
)

```


```{r, echo=FALSE}
df.fit2 <- df.fit %>% 
  filter(Deaths_per_pop100 < 0.6, GDP_2020 < 100000)

fit <- lm(Pop_fully_vaccinated ~ Cases_per_pop100 + Deaths_per_pop100 + GDP_2020, data=df.fit2)

#define weights to use
wt <- 1 / lm(abs(fit$residuals) ~ fit$fitted.values)$fitted.values^2

#perform weighted least squares regression
fit.wls <- lm(Pop_fully_vaccinated ~ Cases_per_pop100 + Deaths_per_pop100 + GDP_2020, data = df.fit2, weights=wt)

fit.wls.coefficients <- summary(fit.wls)$coefficients

rownames(fit.wls.coefficients) <- c("(Intercept)", "Cases per pop %",	"Deaths per pop %", "GDP")

fit.wls.coefficients %>%
  kbl(caption = "Table 5. Updated WLS model coefficients for Pop fully vaccinated %.") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```


# Session info {-}

```{r}
sessionInfo()
```